### ISSUE TITLE
Cant load skill because of failure lambda

### ISSUE THREAD

**Issue by 007hiho007** [tartanguru/alexa-assistant-instructions#44]
Hi,

When i load google on my alexa i got an error. 

Attached a picture... does anyone knows how to solve it ?
![20200222_112059](https://user-images.githubusercontent.com/61327246/75090663-7028c780-5565-11ea-95e8-f2ad7b6b0f2c.jpg)

**Comment by maxidico** [comment]
Same here.  Does anyone have any idea how to fix this problem?

**Comment by Alessandro891** [comment]
I am experiencing this problem me too. Has anyone managed to find a solution?

**Comment by Daz95** [comment]
Went and checked logs in AWS CloudWatch and found that it's because of the mismatched Node.js versions:

2021-04-14T12:05:41.928Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Error",
    "errorMessage": "The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 48. This version of Node.js requires\nNODE_MODULE_VERSION 72. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).",
    "stack": [
        "Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'",
        "was compiled against a different Node.js version using",
        "NODE_MODULE_VERSION 48. This version of Node.js requires",
        "NODE_MODULE_VERSION 72. Please try re-compiling or re-installing",
        "the module (for instance, using `npm rebuild` or `npm install`).",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)",
        "    at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)"
    ]
}
