### ISSUE TITLE
Stack won't create, nodejs6.10 no longer supported

### ISSUE THREAD

**Issue by dmwilson220** [tartanguru/alexa-assistant-instructions#45]
Hi, just tried setting this up to use with my Echo Frames. When creating the stack, it finished rather quickly, I checked the output and didn't see any issues, went back to events and noticed the stack listed CREATE_FAILED.

This error posted:

The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException

Thanks

**Comment by portimor** [comment]
I have the same error and when you change to this new node version (nodejs12.x) the stack creation finish ok but when you try to use the skill the lambda says this:

`{
    "errorType": "Error",
    "errorMessage": "The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 48. This version of Node.js requires\nNODE_MODULE_VERSION 72. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).",
    "stack": [
        "Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'",
        "was compiled against a different Node.js version using",
        "NODE_MODULE_VERSION 48. This version of Node.js requires",
        "NODE_MODULE_VERSION 72. Please try re-compiling or re-installing",
        "the module (for instance, using `npm rebuild` or `npm install`).",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)",
        "    at Module.load (internal/modules/cjs/loader.js:1002:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:901:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1044:19)",
        "    at require (internal/modules/cjs/helpers.js:77:18)",
        "    at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)",
        "    at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)",
        "    at Module._compile (internal/modules/cjs/loader.js:1158:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)",
        "    at Module.load (internal/modules/cjs/loader.js:1002:32)"
    ]
}`

Any suggestions, please?
Thanks a lot.

**Comment by PakoGrimj** [comment]
> I have the same error and when you change to this new node version (nodejs12.x) the stack creation finish ok but when you try to use the skill the lambda says this:
> 
> `{ "errorType": "Error", "errorMessage": "The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 48. This version of Node.js requires\nNODE_MODULE_VERSION 72. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild`or`npm install`).", "stack": [ "Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'", "was compiled against a different Node.js version using", "NODE_MODULE_VERSION 48. This version of Node.js requires", "NODE_MODULE_VERSION 72. Please try re-compiling or re-installing", "the module (for instance, using `npm rebuild`or`npm install`).", " at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)", " at Module.load (internal/modules/cjs/loader.js:1002:32)", " at Function.Module._load (internal/modules/cjs/loader.js:901:14)", " at Module.require (internal/modules/cjs/loader.js:1044:19)", " at require (internal/modules/cjs/helpers.js:77:18)", " at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)", " at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)", " at Module._compile (internal/modules/cjs/loader.js:1158:30)", " at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)", " at Module.load (internal/modules/cjs/loader.js:1002:32)" ] }`
> 
> Any suggestions, please?
> Thanks a lot.

hello how did you do to change node version (nodejs12.x)?

**Comment by eammoury** [comment]
Anyone solved this problem ?

**Comment by DiGilli** [comment]
Hi all,
Same problem here...in short the following error causing a rollbakc resulting in the stack not being created:
_"The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 89d68ce2-bddd-43ce-8972-c3c56d6feba9)"_

Would be grateful for any advice how/where to solve this issue please.
Many thanks in advance!

**Comment by theunf** [comment]
Tried with the version 12 but got app errrors. ;/

**Comment by snadeau89** [comment]
No updates on this issue yet?

**Comment by 1liminal1** [comment]
Any updates?

**Comment by s12321** [comment]
> > I have the same error and when you change to this new node version (nodejs12.x) the stack creation finish ok but when you try to use the skill the lambda says this:
> > `{ "errorType": "Error", "errorMessage": "The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 48. This version of Node.js requires\nNODE_MODULE_VERSION 72. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild`or`npm install`).", "stack": [ "Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'", "was compiled against a different Node.js version using", "NODE_MODULE_VERSION 48. This version of Node.js requires", "NODE_MODULE_VERSION 72. Please try re-compiling or re-installing", "the module (for instance, using `npm rebuild`or`npm install`).", " at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)", " at Module.load (internal/modules/cjs/loader.js:1002:32)", " at Function.Module._load (internal/modules/cjs/loader.js:901:14)", " at Module.require (internal/modules/cjs/loader.js:1044:19)", " at require (internal/modules/cjs/helpers.js:77:18)", " at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)", " at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)", " at Module._compile (internal/modules/cjs/loader.js:1158:30)", " at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)", " at Module.load (internal/modules/cjs/loader.js:1002:32)" ] }`
> > Any suggestions, please?
> > Thanks a lot.
> 
> hello how did you do to change node version (nodejs12.x)?

This is what i did the test:   

1. download from  https://s3-eu-west-1.amazonaws.com/googleassistantskillcloudformationbucket/cloudformation.json
2. change line 192  to "Runtime": "nodejs12.x", save the json file and choose upload the file instead of S3 link
3. the result can bypass the error of installation, successfully enable the skill, but get a fail response from lambda with error "The target Lambda application returned a failure response"

If anyone have time to look at the issue. The current runtime on aws can change to back to node.js 10.x after installation, but come with the same response. 

Not sure if anyone installed at node.js 6.10 and currently is successfully running at node.js 12.x.

**Comment by 1liminal1** [comment]
Yes, I actually found all instructions in issue 95. But if you have followed this guide and then tried to change and re-upload the template. I found it didn't work and I deleted everything on the amazon side and started again. This worked

**Comment by shahiltp** [comment]
any updates?

**Comment by bhafer** [comment]
The project appears to be abandoned.
:(
