### ISSUE TITLE
New updated instructions?

### ISSUE THREAD

**Issue by ifuchs** [tartanguru/alexa-assistant-instructions#46]
I tried to follow the instructions but many of the AWS (and Google) screens have changed and it is not entirely obvious how to proceed. Also, there is a section on Google about Consent that is not covered. Is there an updated set of instructions? If not, has anyone been able to install the google assistant recently?

**Comment by bhafer** [comment]
It's worst than that. The nodejs code doesn't work with an AWS-supported version anymore. :/
Hoping this project gets an update soon.
It was awesome when it used to work!

**Comment by Alessandro891** [comment]
He changed quite a bit. Also nodejs, I changed it but it still doesn't work after the steps.
there is a problem Lambda.

skill alert Endpoint:

**You must create your own AWS Lambda or HTTPS endpoint for your skill to pass certification and be published. You can refer to instructions for setting up an endpoint or choose to convert your skill to an Alexa-hosted Skill to benefit from manager backend resources.**

google OAuth consent screen:

**We are currently experiencing some service outages and are unable to provide information on quotas.**

Alexa replies after connecting her to the google profile:

**There was a problem with the requested skill response**

I don't know what to do anymore, I'm trying everything. I will wait for an eventual update. We hope well. Thanks to who will give me a tip.

**Comment by FlattusBlastus** [comment]
Display Interfaces will be gone shortly. Can the instructions be updated to account for APL?

**Comment by Daz95** [comment]
> Display Interfaces will be gone shortly. Can the instructions be updated to account for APL?

Are you getting it to work currently anyway with the node issue?

2021-04-14T12:05:41.928Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Error",
    "errorMessage": "The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 48. This version of Node.js requires\nNODE_MODULE_VERSION 72. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).",
    "stack": [
        "Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'",
        "was compiled against a different Node.js version using",
        "NODE_MODULE_VERSION 48. This version of Node.js requires",
        "NODE_MODULE_VERSION 72. Please try re-compiling or re-installing",
        "the module (for instance, using `npm rebuild` or `npm install`).",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)",
        "    at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)"
    ]
}

**Comment by elvistony** [comment]
It seems like a similar issue explained [here](https://github.com/tartanguru/alexa-assistant/issues/95)

> Are you getting it to work currently anyway with the node issue?
> 
> 2021-04-14T12:05:41.928Z undefined ERROR Uncaught Exception {
> "errorType": "Error",
> "errorMessage": "The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 48. This version of Node.js requires\nNODE_MODULE_VERSION 72. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).",
> ....
